baseURL = 'https://sisaku-security.github.io/sisakulint/'
languageCode = 'en-us'
title = 'sisakulint Document'
publishDir = './public'
enableGitInfo = true

[param]
BookRepo = 'https://github.com/sisaku-security/sisakulint'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'
